// RepoDocs AI — offscreen document. Classic script (loaded after vendored jspdf/docx UMD bundles),
// so it can use window.jspdf / window.docx globals that an MV3 module service worker cannot load directly.

const PAGE_W = 595.28; // A4 pt
const PAGE_H = 841.89;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;

function svgToPng(svgString) {
  return new Promise((resolve, reject) => {
    const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.onload = () => {
      const w = img.naturalWidth || img.width;
      const h = img.naturalHeight || img.height;
      const scale = 2;
      const canvas = document.createElement('canvas');
      canvas.width = w * scale;
      canvas.height = h * scale;
      const ctx = canvas.getContext('2d');
      ctx.scale(scale, scale);
      ctx.drawImage(img, 0, 0, w, h);
      URL.revokeObjectURL(url);
      resolve({ dataUrl: canvas.toDataURL('image/png'), width: w, height: h });
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to rasterize SVG diagram.'));
    };
    img.src = url;
  });
}

function dataUrlToUint8Array(dataUrl) {
  const base64 = dataUrl.split(',')[1];
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function blobToDataUrl(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

function fitImage(maxW, maxH, w, h) {
  const ratio = Math.min(maxW / w, maxH / h, 1);
  return { w: w * ratio, h: h * ratio };
}

// ---------- PDF ----------
function buildPdf({ analysis, sections, images, screenshotDataUrl }) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'pt', format: 'a4', compress: true });
  const meta = analysis.meta || {};
  const today = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

  function footer(pageLabel) {
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text(`RepoDocs AI  ·  ${analysis.owner}/${analysis.repo}`, MARGIN, PAGE_H - 28);
    doc.text(pageLabel, PAGE_W - MARGIN, PAGE_H - 28, { align: 'right' });
  }

  function sectionPage(title, text, pageNum) {
    doc.addPage();
    doc.setFillColor(15, 17, 23);
    doc.rect(0, 0, PAGE_W, 70, 'F');
    doc.setTextColor(251, 191, 36);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(title, MARGIN, 45);
    doc.setTextColor(30, 30, 30);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(text || '', CONTENT_W);
    doc.text(lines, MARGIN, 110);
    footer(String(pageNum));
  }

  function imagePage(title, img, pageNum, captionText) {
    doc.addPage();
    doc.setFillColor(15, 17, 23);
    doc.rect(0, 0, PAGE_W, 70, 'F');
    doc.setTextColor(251, 191, 36);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(title, MARGIN, 45);
    if (img) {
      const { w, h } = fitImage(CONTENT_W, PAGE_H - 200, img.width, img.height);
      const x = MARGIN + (CONTENT_W - w) / 2;
      doc.addImage(img.dataUrl, 'PNG', x, 100, w, h);
      if (captionText) {
        doc.setTextColor(110, 110, 110);
        doc.setFontSize(9);
        doc.text(captionText, PAGE_W / 2, 100 + h + 20, { align: 'center' });
      }
    }
    footer(String(pageNum));
  }

  // Cover
  doc.setFillColor(15, 17, 23);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
  doc.setTextColor(251, 191, 36);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(30);
  doc.text('Project Documentation', PAGE_W / 2, 320, { align: 'center' });
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(`${analysis.owner}/${analysis.repo}`, PAGE_W / 2, 360, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(180, 180, 180);
  const desc = doc.splitTextToSize(meta.description || 'AI-generated repository analysis and breakdown.', 420);
  doc.text(desc, PAGE_W / 2, 400, { align: 'center' });
  doc.setFontSize(10);
  doc.setTextColor(140, 140, 140);
  doc.text(`Generated by RepoDocs AI  ·  ${today}`, PAGE_W / 2, PAGE_H - 60, { align: 'center' });

  let p = 2;
  sectionPage('Executive Overview', sections['Executive Overview'], p++);
  sectionPage('Architecture & Tech Stack', sections['Architecture & Tech Stack'], p++);
  imagePage('Repository Structure', images.structure, p++, 'Top-level folder & file layout (truncated for readability).');
  sectionPage('Features & Functionality', sections['Features & Functionality'], p++);
  imagePage('Feature Mindmap', images.mindmap, p++, 'Key capabilities derived from the codebase, manifest, and README.');
  sectionPage('Setup & Usage', sections['Setup & Usage'], p++);
  sectionPage('Testing & Quality Notes', sections['Testing & Quality Notes'], p++);
  if (screenshotDataUrl) {
    doc.addPage();
    doc.setFillColor(15, 17, 23);
    doc.rect(0, 0, PAGE_W, 70, 'F');
    doc.setTextColor(251, 191, 36);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Live Application', MARGIN, 45);
    doc.addImage(screenshotDataUrl, 'PNG', MARGIN, 100, CONTENT_W, CONTENT_W * 0.6);
    footer(String(p));
    p++;
  }
  sectionPage('Conclusion & Recommendations', sections['Conclusion & Recommendations'], p++);

  return doc.output('datauristring');
}

// ---------- DOCX ----------
async function buildDocx({ analysis, sections, images, screenshotDataUrl }) {
  const { Document, Packer, Paragraph, TextRun, ImageRun, HeadingLevel, AlignmentType, PageBreak } = window.docx;
  const meta = analysis.meta || {};
  const today = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

  function heading(text) {
    return new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { after: 200 } });
  }
  function body(text) {
    return new Paragraph({ children: [new TextRun((text || '').toString())], spacing: { after: 200 } });
  }
  function image(img, maxW = 480) {
    if (!img) return new Paragraph({ text: '' });
    const ratio = Math.min(maxW / img.width, 1);
    return new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new ImageRun({
          type: 'png',
          data: dataUrlToUint8Array(img.dataUrl),
          transformation: { width: img.width * ratio, height: img.height * ratio },
        }),
      ],
    });
  }

  const children = [
    new Paragraph({ text: 'Project Documentation', heading: HeadingLevel.TITLE, alignment: AlignmentType.CENTER }),
    new Paragraph({ text: `${analysis.owner}/${analysis.repo}`, heading: HeadingLevel.HEADING_2, alignment: AlignmentType.CENTER }),
    new Paragraph({ text: meta.description || 'AI-generated repository analysis and breakdown.', alignment: AlignmentType.CENTER, spacing: { after: 300 } }),
    new Paragraph({ text: `Generated by RepoDocs AI · ${today}`, alignment: AlignmentType.CENTER, spacing: { after: 600 } }),
    new Paragraph({ children: [new PageBreak()] }),

    heading('Executive Overview'), body(sections['Executive Overview']),
    heading('Architecture & Tech Stack'), body(sections['Architecture & Tech Stack']),
    heading('Repository Structure'), image(images.structure),
    heading('Features & Functionality'), body(sections['Features & Functionality']),
    heading('Feature Mindmap'), image(images.mindmap),
    heading('Setup & Usage'), body(sections['Setup & Usage']),
    heading('Testing & Quality Notes'), body(sections['Testing & Quality Notes']),
  ];

  if (screenshotDataUrl) {
    children.push(heading('Live Application'));
    const bytes = dataUrlToUint8Array(screenshotDataUrl);
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new ImageRun({ type: 'png', data: bytes, transformation: { width: 460, height: 280 } })],
    }));
  }

  children.push(heading('Conclusion & Recommendations'), body(sections['Conclusion & Recommendations']));

  const doc = new Document({ sections: [{ properties: {}, children }] });
  const blob = await Packer.toBlob(doc);
  return blobToDataUrl(blob);
}

// ---------- message handling ----------
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg?.target !== 'offscreen') return;

  (async () => {
    try {
      if (msg.type === 'rasterize') {
        const structure = await svgToPng(msg.payload.structureSvg);
        const mindmap = await svgToPng(msg.payload.mindmapSvg);
        sendResponse({ result: { structure, mindmap } });
      } else if (msg.type === 'build-pdf') {
        const result = buildPdf(msg.payload);
        sendResponse({ result });
      } else if (msg.type === 'build-docx') {
        const result = await buildDocx(msg.payload);
        sendResponse({ result });
      } else {
        sendResponse({ error: 'Unknown offscreen message type: ' + msg.type });
      }
    } catch (err) {
      sendResponse({ error: err.message });
    }
  })();

  return true;
});
